# Generated by Django 4.2.5 on 2023-10-07 10:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contect',
            new_name='Contact',
        ),
    ]
