# Generated by Django 4.2.5 on 2023-10-11 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0003_employee_feedback_rating_scheme_offers'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicle_manage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('truck_type', models.CharField(max_length=50)),
                ('truck_size', models.CharField(max_length=40)),
                ('truck_capacity', models.CharField(max_length=40)),
                ('truck_weight', models.CharField(max_length=30)),
                ('photo', models.FileField(default='', max_length=200, upload_to='transportapp/truck_pic')),
            ],
        ),
    ]
