# Generated by Django 4.2.5 on 2023-10-19 06:56

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0006_check_fare_user_login'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_id', models.CharField(max_length=40)),
                ('reciever_id', models.CharField(max_length=40)),
                ('subject', models.CharField(max_length=40)),
                ('massage', models.CharField(max_length=100)),
                ('sender_status', models.CharField(max_length=40)),
                ('reciever_status', models.CharField(max_length=40)),
                ('date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.DeleteModel(
            name='user_login',
        ),
    ]
