# Generated by Django 4.2.5 on 2023-10-20 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0007_user_message_delete_user_login'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_message',
            old_name='massage',
            new_name='message',
        ),
    ]
