# Generated by Django 4.2.5 on 2023-10-20 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0008_rename_massage_user_message_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_message',
            old_name='reciever_id',
            new_name='receiver_id',
        ),
    ]
