# Generated by Django 4.2.5 on 2023-10-20 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0009_rename_reciever_id_user_message_receiver_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user_message',
            old_name='reciever_status',
            new_name='receiver_status',
        ),
    ]
