# Generated by Django 4.2.5 on 2023-10-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0010_rename_reciever_status_user_message_receiver_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('driver_id', models.CharField(max_length=40)),
                ('truck_type', models.CharField(max_length=50)),
                ('pick', models.CharField(max_length=200)),
                ('drop', models.CharField(max_length=200)),
            ],
        ),
        migrations.AlterField(
            model_name='user_message',
            name='receiver_status',
            field=models.CharField(default='False', max_length=40),
        ),
        migrations.AlterField(
            model_name='user_message',
            name='sender_status',
            field=models.CharField(default='False', max_length=40),
        ),
    ]
