# Generated by Django 4.2.5 on 2023-10-22 18:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0011_vehicle_booking_alter_user_message_receiver_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Goods_type',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='vehicle_booking',
            name='booking_date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='vehicle_booking',
            name='booking_status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='vehicle_booking',
            name='delivery_date',
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AddField(
            model_name='vehicle_booking',
            name='paid_amount',
            field=models.CharField(default=False, max_length=30),
        ),
    ]
