# Generated by Django 4.2.5 on 2023-11-06 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0012_goods_type_vehicle_booking_booking_date_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle_booking',
        ),
    ]
