# Generated by Django 4.2.5 on 2023-11-06 11:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('transportapp', '0013_delete_vehicle_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle_booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=40)),
                ('veh_id', models.CharField(max_length=5)),
                ('driver_id', models.CharField(max_length=40)),
                ('truck_type', models.CharField(max_length=50)),
                ('pick', models.CharField(max_length=200)),
                ('drop', models.CharField(max_length=200)),
                ('item_type', models.CharField(max_length=40)),
                ('delivery_date', models.CharField(max_length=10)),
                ('booking_date', models.CharField(max_length=10)),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('paid_amount', models.CharField(max_length=30)),
                ('booking_status', models.BooleanField(default=False)),
            ],
        ),
    ]
